meta_product_name: "Paritize"
meta_title: "Paritize - Gender Diviersity in focus."
meta_description: "Paritize is a tool to improve transparency surrounding gender equality in the workplace."
meta_image: "paritize_meta.png" # should exist in `app/assets/images/`
